### ISSUE TITLE
get_feature_names of FeatureFunctionTransformer fails when n_jobs > 1

### ISSUE THREAD

**Issue by jbschiratti** [mne-tools/mne-features#12]
@GuillaumeCorda and I noticed the following bug:
```
import numpy as np
from mne_features.feature_extraction import extract_features

rng = np.random.RandomState(42)
sfreq = 256.
data = rng.standard_normal((10, 20, int(sfreq)))

sel_funcs = ['mean']
df = extract_features(data, sfreq, sel_funcs, n_jobs=-1, return_as_df=True)
```
outputs:
```
Traceback (most recent call last):
  File "/cal/homes/jbschiratti/mne-features/mne_features/tests/test.py", line 9, in <module>
    df = extract_features(data, sfreq, sel_funcs, n_jobs=-1, return_as_df=True)
  File "/cal/homes/jbschiratti/mne-features/mne_features/feature_extraction.py", line 262, in extract_features
    return _format_as_dataframe(Xnew, extractor.get_feature_names())
  File "/cal/homes/jbschiratti/anaconda3/lib/python3.5/site-packages/sklearn/pipeline.py", line 699, in get_feature_names
    trans.get_feature_names()])
  File "/cal/homes/jbschiratti/mne-features/mne_features/feature_extraction.py", line 69, in get_feature_names
    raise ValueError('Call `transform` or `fit_transform` first.')
ValueError: Call `transform` or `fit_transform` first.
```

**Comment by agramfort** [comment]
see https://github.com/mne-tools/mne-features/pull/13

**Comment by jbschiratti** [comment]
Thank you @agramfort

**Comment by GuillaumeCorda** [comment]
Merci !

----- Mail original -----
De: "Alexandre Gramfort" <notifications@github.com>
À: "mne-tools/mne-features" <mne-features@noreply.github.com>
Cc: "Guillaume Corda" <guillaume.corda@telecom-paristech.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Mercredi 28 Mars 2018 16:38:03
Objet: Re: [mne-tools/mne-features] get_feature_names of FeatureFunctionTransformer fails when n_jobs > 1 (#12)

see https://github.com/mne-tools/mne-features/pull/13

**Comment by agramfort** [comment]
feel free to merge
