### ISSUE TITLE
Multiprocessing while feature extraction

### ISSUE THREAD

**Issue by talhaanwarch** [mne-tools/mne-features#55]
Greetings, Every one. First of all thanks for such an amazing package.  I am trying to find features from a data shape of `100,64,3072` and it takes a lot of time. So i decided to go for multiprocessing. 
I have tried multiprocessing across different subjects, and it work faster than sequential one, but with reduced channels (9 channels). 

Now i am trying to multiprocessing on single subject, but across multiple channels.
Here is my code

```import numpy as np
from mne_features.feature_extraction import FeatureExtractor
import time
from multiprocessing import Process,current_process,Pool

feature=['app_entropy', 'decorr_time', 'energy_freq_bands', 'higuchi_fd', 'hjorth_complexity', 'hjorth_complexity_spect', 'hjorth_mobility', 'hjorth_mobility_spect', 'hurst_exp', 'katz_fd', 'kurtosis', 'line_length', 'mean', 'pow_freq_bands', 'ptp_amp', 'samp_entropy', 'skewness', 'spect_entropy', 'spect_slope', 'std', 'svd_entropy', 'svd_fisher_info', 'teager_kaiser_energy', 'variance', 'wavelet_coef_energy', 'zero_crossings', 'max_cross_corr', 'nonlin_interdep', 'phase_lock_val', 'spect_corr', 'time_corr']
fe = FeatureExtractor(sfreq=1024, selected_funcs=feature)

#print("Number of processors: ", mp.cpu_count())
def cal_feature(ch):
    data= np.random.randint(0, 100, size=(100, 64, 3072))

    return fe.fit_transform(data[:,ch,:])


if __name__ == '__main__':

    start = time.time()
    ch=[i for i in range(64)]
    with Pool(12) as p:
        result = p.map(cal_feature,(ch) )
    print(time.time()-start)
```
If i replace `fe.fit_transform(data[:,ch,:])` with `np.mean(fe.fit_transform(data[:,ch,:],-1)` every thing works fine. Hence i assumed that there is no issue with multiprocessing code
I am getting following error
````
Traceback (most recent call last):

  File "<ipython-input-3-1b73aa731887>", line 1, in <module>
    runfile('F:/Scizhophrenia/4- feature extraction multiscript a.py', wdir='F:/Scizhophrenia')

  File "C:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "F:/Scizhophrenia/4- feature extraction multiscript a.py", line 33, in <module>
    result = p.map(cal_feature,(ch) )

  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()

  File "C:\Anaconda3\lib\multiprocessing\pool.py", line 657, in get
    raise self._value

IndexError: too many indices for array````

**Comment by agramfort** [comment]
we tend to use joblib for parallel computation

can you try with joblib?

>

**Comment by talhaanwarch** [comment]
I have tried this, but still getting an error. Do you have some sample problem done using parallel processing. Here is what i have done
```from joblib import Parallel, delayed
import numpy as np
import time
from mne_features.feature_extraction import FeatureExtractor
feature=['mean','variance','std']
fe = FeatureExtractor(sfreq=1024, selected_funcs=feature)



def f(x):
    return fe.fit_transform(x)

st=time.time()
l =np.random.randint(0, 100, size=(100, 64, 3000))
results = Parallel(n_jobs=-1)(delayed(f)(i) for i in l)
print(time.time()-st)```

`Traceback (most recent call last):

  File "<ipython-input-12-b1dba799a355>", line 16, in <module>
    results = Parallel(n_jobs=-1)(delayed(f)(i) for i in l)

  File "C:\Anaconda3\lib\site-packages\joblib\parallel.py", line 934, in __call__
    self.retrieve()

  File "C:\Anaconda3\lib\site-packages\joblib\parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))

  File "C:\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)

  File "C:\Anaconda3\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()

  File "C:\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception

IndexError: too many indices for array`

**Comment by agramfort** [comment]
are you in a notebook? what version of joblib are you using?
are you in a main block?

>

**Comment by talhaanwarch** [comment]
i am using spyder, joblib version is 0.13.2.

**Comment by agramfort** [comment]
can you share a full script in https://gist.github.com/
so one of us can try to replicate?

**Comment by talhaanwarch** [comment]
https://gist.github.com/talhaanwarch/9d750a4f2a82f5ed72a88ba7cfa38533 check it here please

**Comment by agramfort** [comment]
please fix your script. Make sure it works with n_jobs=1 before blaming
joblib or multiprocessing

>

**Comment by talhaanwarch** [comment]
i have updated my gist with a numpy function instead of feature extraction function and it work well, that why i assume that, there is some issue in feature extraction with parallel processing across columns.

**Comment by agramfort** [comment]
the pb is that you pass a 2d array to a function that requires a 3d array. If you have 1 sensors add a dimension of length one.
